### ISSUE TITLE
texture.SaveAsPng does not support DXT formats

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACViewer#70]
Reproduce: 
Open Setup 0x020019FF (door)
Select, Tools / Export and watch the whole thing crash to the ground in FileExport.cs: https://github.com/ACEmulator/ACViewer/blob/4a6aaccbd01da550adab5558f262aac9b5c3dad4/ACViewer/FileExport.cs#L255

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACViewer/pull/69
