### ISSUE TITLE
Collada Import Fail into Blender

### ISSUE THREAD

**Issue by Vermino** [ACEmulator/ACViewer#76]
![dae fail](https://github.com/ACEmulator/ACViewer/assets/1296796/cb1ae443-23ad-4324-aad3-53784fba9681)

When importing 02000001 as a .dae into blender, I am getting:

Schema validation (Error): Critical error: ERROR_XML_PARSER_ERROR Additional: Start tag expected, '<' not found

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACViewer/pull/77

Thanks for reporting the issue!

**Comment by Vermino** [comment]
Awesome! It works!
